UI: add containing `View` for each `Label`
compnerd/swift-win32 pull request #306
Opened 2020-12-05 15:39 UTC by egorzhdan

`WC_STATIC` control doesn't receive events like `WM_CONTEXTMENU`. To be able to handle those events, let's create containing views for `WC_STATIC` instances.

2020-12-05 23:27 UTC, compnerd commented
Hmm, can we not just adjust the owner window for label and handle the event?

2020-12-06 17:22 UTC, egorzhdan commented
I think it would significantly complicate the `Window` event handling logic: we'd have to go through all the labels in all the components inside the window, find the labels that correspond to the coordinates of the mouse click, filter out the hidden ones, and find the topmost enabled label.
Similar logic would be required for other interactions to work, like drag & drop.

I believe it would be better to delegate this work to the OS, just like for all the other components.

2020-12-19 00:28 UTC, compnerd commented
Thinking more about this, is this really a special case?  Will this be needed for all the controls?  Can we avoid this by doing a custom draw?

2020-12-21 17:26 UTC, egorzhdan commented
> is this really a special case

I think so, it seems `WC_STATIC` is the only built-in control that doesn't receive all the click events. At least I couldn't find another such control.

> Will this be needed for all the controls?

Nope, this is only needed for `WC_STATIC`.
Actually I've just noticed that `ImageView` also relies on `WC_STATIC`, so it might need a similar workaround as `Label`.

> Can we avoid this by doing a custom draw?

Not sure... I'll try.

> The hit testing can be delegated to the OS

This would be great, this way there won't be the need to reimplement the system event dispatch logic. I don't really know how to do it though...


A similar issue will probably arise once drag-and-drop or other interactions are implemented – these static controls won't be receiving the events properly.

2021-03-31 00:59 UTC, compnerd commented
This would be good to get rebased and prepared to be merged, at least for the Label case.  We should figure out how to do this more generically at some point.

2021-03-31 10:16 UTC, egorzhdan commented
Just rebased this, and it still works for me – the context menus show up on a right-click on labels as expected.
I haven't tried to abstract this logic away from `Label` in this PR, but I think it would eventually be needed to support context menus for `Image`.

2021-03-31 15:51 UTC, compnerd commented
Hey @egorzhdan, sorry to do this to you, but could you rebase this on top of #434 as I think that is a pretty simple change and I was thinking about a bit more tweaking to this change?

2021-03-31 15:59 UTC, compnerd requested changes

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  fileprivate var text: String?
```suggestion
  public var text: String?
```

The type itself is `fileprivate` so it is okay for this to be `public`

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  fileprivate init(frame: Rect) {
```suggestion
  public init(frame: Rect) {
```

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +fileprivate class Win32Label: View {
```suggestion
fileprivate class LabelView: View {
```

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  private let win32Label: Win32Label
```suggestion
  private let view: LabelView
```

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +    win32Label = Win32Label(frame: Rect(origin: .zero, size: frame.size))
```suggestion
    self.view = LabelView(frame: Rect(origin: .zero, size: frame.size))
```

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +    addSubview(win32Label)
```suggestion
    self.addSubview(self.view)
```

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
Are `font`, `text` the only properties we need to forward?

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
I think that we should override `subviews` as well to hide the container, WDYT?

2021-03-31 15:59 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
Does it make sense to make sure that the label has a transparent background?

2021-04-03 02:48 UTC, compnerd commented
Thinking about this a bit further, is there any advantage to actually deriving the label from `View`?  That is, perhaps it makes more sense to just manually create the `WC_STATIC` window locally and add it as a child and forget about it entirely.  We should be able to just handle the resize as `didSet` observers on the frame.

2021-04-03 18:11 UTC, egorzhdan commented
If we get rid of the `LabelView` component, we'll have to reimplement some of `View`'s logic, namely `font` & `text` properties, for the manually created `WC_STATIC` component. Do you think that would still be a better option?

2021-04-03 18:32 UTC, egorzhdan commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
I think yes, the rest of them don't seem to affect the internal `WC_STATIC` component.

2021-04-03 18:32 UTC, egorzhdan commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
Oh yeah you're right, I haven't thought about that.

2021-04-03 18:32 UTC, egorzhdan commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
I guess it does, but `View.backgroundColor` isn't implemented yet, and I think `Color.clear` is mentioned in the doc comments but isn't defined. Perhaps this could be a part of the future change that will bring support for background colors? :)

2021-04-04 00:09 UTC, compnerd commented
> If we get rid of the `LabelView` component, we'll have to reimplement some of `View`'s logic, namely `font` & `text` properties, for the manually created `WC_STATIC` component. Do you think that would still be a better option?

True, but, we end up having to do that in senses anyways - we forward the settings to the subview.  At the end of the day, we just need to change the hWnd that the messages are sent to, so that seems no more expensive really, it just is a matter of inlining the call.  If I am not mistaken, instead of forwarding the properties, we will just inline the `SendMessageW` for those cases right?

2021-04-04 00:09 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
Sounds good.

2021-04-04 00:10 UTC, compnerd commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +  }
The alternative discussed below cleverly sidesteps the issue.

2021-04-05 20:12 UTC, egorzhdan commented
> we just need to change the hWnd that the messages are sent to

Hmm, do you mean changing `self.hWnd` to the `WS_STATIC` component's hWnd? I don't think that would work, since the parent component would get overwritten when adding the label as a subview to another view.

> it just is a matter of inlining the call

So basically calling all the WinSDK methods for creating/repositioning the `WS_STATIC` component from `Label.init`?

2021-04-05 21:58 UTC, compnerd commented
> Hmm, do you mean changing `self.hWnd` to the `WS_STATIC` component's hWnd? I don't think that would work, since the parent component would get overwritten when adding the label as a subview to another view.
> 
> >

No, that won't work for exactly the reason you mention.  However, rather than having the properties forward to another view, which then just invokes `SendMessageW`, we can inline those into the properties instead and use the stashed HWND for the static label.  You counted a small set of properties which needed to be forwarded, so this should be equivalent.

> So basically calling all the WinSDK methods for creating/repositioning the `WS_STATIC` component from `Label.init`?

No, the thought that I had was actually the insight that we dont care about the settings for the `LabelView`.  The only things we care about are:
- Font
- Foreground Color
- Position

If we set the background color to clear, instead of forwarding the font and foreground color we send the proper message to the emebdded view, and set a property observer on the position, we can entirely ignore the embedded window.

2021-04-06 16:34 UTC, egorzhdan commented
Got it, thanks! I think this should now work the way you expect.

2021-04-06 18:11 UTC, compnerd reviewed
I think that this is actually going to be far more important than I first expected.  The `Label` type really should be a composite type which doesn't leak the members.  Thank you so much for working on this!

2021-04-06 19:11 UTC, egorzhdan commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +    _ = SetWindowLongW(self.staticHWnd, WinSDK.GWL_STYLE, staticStyle)
Yeah, we actually only need `WS_CHILD` here, so I made it static.

2021-04-06 19:11 UTC, egorzhdan commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +                       UINT(SWP_NOZORDER | SWP_FRAMECHANGED))
We can use the parent rect indeed. Fixed it.

2021-04-06 19:11 UTC, egorzhdan commented on Sources/SwiftWin32/Views and Controls/Label.swift
> +                                      nil, nil, GetModuleHandleW(nil), nil)!
Fixed

2021-04-06 20:44 UTC, compnerd approved these changes
Thanks!  I think that this can be simplified a bit further, but we can do that in a follow up clean up.  Assuming it also builds with CMake, I don't think that we need to push this out any further.

2021-04-06 20:44 UTC, compnerd commented
/azp run VS2019

2021-04-06 20:51 UTC, compnerd commented
Ugh, I think looking into the CMake build can happen later.

2021-04-06 20:51 UTC, merged