Hello World sample: Added a title and a hello world label
compnerd/swift-win32 pull request #376
Opened 2021-01-17 00:16 UTC by yostane

Hello,
I have added a title and a label to the "hello world" example.
Best regards,

2021-01-17 20:53 UTC, compnerd requested changes
I can see some value to adding the title/label, but at the same time, this is intended to just be a skeleton to setup a window.  What exactly is this trying to achieve or what is the motivation here?

Could you please squash the changes into a single commit and add that information into the commit message?

2021-01-17 20:53 UTC, compnerd commented on Examples/HelloWorld/HelloWorld.swift
> +    window.rootViewController?.title = "swift-win32 Hello World"
Would you mind using "Swift/Win32 Hello World" instead?
```suggestion
    window.rootViewController?.title = "Swift/Win32 Hello World"
```

2021-01-17 20:53 UTC, compnerd commented on Examples/HelloWorld/HelloWorld.swift
> +    label.text = "Hello World with some Swift ❤️"
Let's make this purely "Hello World!"  Is there some particular reason to include additional text?  Was there something that you wanted this to demonstrate?
```suggestion
    label.text = "Hello World!"
```

2021-01-18 16:47 UTC, yostane commented
Ok, I'll create another PR with the requested information

2021-01-18 16:47 UTC, closed without merging