Fix for compnerd/swift-win32/issues/272
compnerd/swift-win32 pull request #378
Opened 2021-01-26 20:33 UTC by yostane

- Application main loads the delegate name from info.plist
- main: remove delegate param since it's loaded from info.plist
- Calculator: copy info.plist in CMakeLists (calculator exe was not loading before that)

2021-01-26 21:24 UTC, compnerd requested changes
Thanks for the change!  Would you mind splitting out the CMake change for the `Info.plist` copying to a separate change?

2021-01-26 21:24 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +                            _ application: String?) -> Int32 {
I would prefer to retain the ability to explicitly specify the delegate if the user so desires.  I don't think that it really adds much in terms of complexity.  If one is not specified, we can fallback to the `Info.plist` value, and if one is not present, we can default the delegate.

2021-01-26 21:24 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +  if let delegate = Application.shared.information?.scene?.configurations?[SceneSession.Role.windowApplication.rawValue]?.first?.delegate {
The scene delegate and application delegates are separate (or can be).  I don't follow the reasoning for initializing the application delegate from the scene delegate.

2021-01-27 20:44 UTC, yostane commented
> Thanks for the change! Would you mind splitting out the CMake change for the `Info.plist` copying to a separate change?

Ok, I'll close this one and make separate PRs

2021-01-27 20:44 UTC, closed without merging