Added support for NSPrincipalClass
compnerd/swift-win32 pull request #385
Opened 2021-02-14 21:57 UTC by yostane

- info.plist is loaded more early in ApplicationMain to allow losing the App class from NSPrincipalClass if avaialble
- Made Application and Responder open to allow for user-defined Application subclass
- Added example app that defines NSPrincipalClass. The example contains also a small readme
- Added an indentation in Information enums as used in swift doc https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

2021-02-18 17:13 UTC, compnerd requested changes
Thanks!

I'm not sure if the example for the custom principal class is particularly valuable.  I don't think that many people would be using that.  If its particularly important, we can always just change the UICatalog demo.

2021-02-18 17:13 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to find info.plist")
I don't think that this really adds much in terms of information - can we add some additional information about the failure?  I think that it should be okay if no `Info.plist` is there by default for the most trivial application.  This would however log a warning.

2021-02-18 17:13 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
This warning has nothing actionable.  If we cannot explain why the load failed, I don't think that we should be logging a warning here.

2021-02-18 17:13 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +func getApplicationClassName(userPassedApp: String?, appInformation: Application.Information?) -> String?{
I don't think that the keyword arguments add any value here.  Why the preference for:
`getApplicationClassName(userPassedApp:appInformation:)` rather than `getApplicationClassName(_:_:)`?

Furthermore, the single line function doesn't add any real clarity:

```swift
  let `class`: String = application ?? (Application.shared.Info?.principalClass ?? "Application")
```
seems much clearer - if the user specified one, it takes precedence, otherwise, the Info.plist defined value does.  And should neither be found, "Application" is the default.

2021-02-18 17:13 UTC, compnerd commented on Sources/SwiftWin32/Application/Information.swift
> +    case delegate = "SceneDelegateClassName"
I don't mind the whitespace change here, but please make that part of a separate commit, that has nothing to do with the handling of the PrincipalClass.

2021-02-18 17:13 UTC, compnerd commented on Sources/SwiftWin32/App and Environment/Application.swift
> +open class Application: Responder {
The change to `open` for this and `Responder` are completely correct, but I don't understand how they are related to handling the `NSPrincipalClass` property.  They should be a separate change IMO.

2021-02-19 20:05 UTC, yostane commented on Sources/SwiftWin32/Application/Information.swift
> +    case delegate = "SceneDelegateClassName"
Indeed :)

2021-02-19 20:09 UTC, yostane commented on Sources/SwiftWin32/App and Environment/Application.swift
> +open class Application: Responder {
Changing to open is a prerequisite for this MR. If Application and Responder are left "public", the developer cannot subclass "Application", and thus, cannot take advantage of NSPrincipalClass. 

We can make this a separate MR that should be merged before this one. If we accept this MR without this change, the compiler would never allow subclassing Application.

Do you prefer a separate MR ? Both replies are ok for me 😄. If yes, I can create the MR.

2021-02-19 20:15 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
Do you mean that we should not log at all or log to a different level (debug, info) ?

2021-02-19 20:19 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
The only information that we have when the gaurd fails is that :

> If path specifies a directory, or if some other error occurs, this method returns nil.

("some other error"  XD)

Can I log this for example: "Failed to load info.plist at (path). The path is a directory, or an unknown error occured" ?

2021-02-19 20:27 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to find info.plist")
About adding informations to the log, the apple documentation says about the return value:

> or nil if the file could not be located.

Can I log this for example ? `Failed to locate optional Info.plist`

2021-02-19 20:29 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +func getApplicationClassName(userPassedApp: String?, appInformation: Application.Information?) -> String?{
Nice, I'll do the modifications 👍

2021-02-19 20:34 UTC, yostane commented
You're welcome 😄 

I created the example mainly for my testing. So, it also ok for me to remove it for now add it later (to UICatalog or in another way) if necessary. 
However, if we do that, will the developer know of this possibility and how to to do it ? I would suggest at least to have some kind of documentation. What do you think ?

2021-02-19 22:25 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to find info.plist")
I don't think that this should be a warning, if you want to log it at a "lower" log level, that is fine.

2021-02-19 22:26 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
How do you determine if it is a directory based on that?  I would say that if you want, you can try to see if FileManager will provide the additional details.  Otherwise, I don't think that this should be logged as a warning.

2021-02-19 22:27 UTC, compnerd commented on Sources/SwiftWin32/App and Environment/Application.swift
> +open class Application: Responder {
Sure, a separate PR for that is perfectly fine.

2021-02-19 22:28 UTC, compnerd commented
Documentation overall is something that would be great to have, but we don't have that currently.  I think that a separate PR to add documentation is a great idea, and I would definitely be excited to see that.

2021-02-20 09:27 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
We can get additional details with : [fileExists(atPath:isDirectory:)](https://developer.apple.com/documentation/foundation/filemanager/1410277-fileexists)

2021-02-20 09:29 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +func getApplicationClassName(userPassedApp: String?, appInformation: Application.Information?) -> String?{
On a second though, I think that we should not use yet `Application.shared.Info?.principalClass` because we are currently trying to load `Application.shared`. That's why I passed the `appInformation` argument.

2021-02-20 09:39 UTC, yostane commented
Before starting writing a documentation, do you have preferences or recommendations about the documentation format / tools and the documentation structure / plan ? In that case, I think that it should be better if you create an issue where you specify those elements. What do you think ?

2021-02-20 09:53 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +func getApplicationClassName(userPassedApp: String?, appInformation: Application.Information?) -> String?{
Loading the app class from :  `Application` because classes are prefixed with app names I guess.

```log
SwiftWin32/ApplicationMain.swift:83: Fatal error: unable to find application class: Application
```

2021-02-20 10:03 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
After some tests, I have found that it if the info.plst is a folder, `Bundle.main.path` fails. So I will just for now reduce the log to debug.

2021-02-20 17:03 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
That seems expensive - you are doing a file system operation to check if it is a directory which doesn't give you any additional information and you should immediately spot.  This is about constructing a standard bundle as defined by Foundation, this is not something specific and special to this framework.  This simply adds clutter and adds unnecessary diagnostic code and log spew.

2021-02-20 17:05 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +func getApplicationClassName(userPassedApp: String?, appInformation: Application.Information?) -> String?{
The changes change the order in which the information is loaded.  If there is a local variable, that is sufficient as a replacement ;-).

```swift
let `class`: String = application ?? (info?.principalClass ?? "Application")
```

2021-02-20 17:13 UTC, compnerd requested changes

2021-02-20 17:13 UTC, compnerd commented on Examples/CMakeLists.txt
> -
Unnecessary change :)

2021-02-20 17:13 UTC, compnerd commented on Sources/SwiftWin32/App and Environment/Application.swift
> +open class Application: Responder {
Rebasing should get rid of this change

2021-02-20 17:13 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +  guard let contents = FileManager.default.contents(atPath: path) else {
I think that unless you have concrete reasons why the file failed to deserialize I think that this is better:

```swift
  var information: Application.Information?
  if let path = Bundle.main.path(forResource: "Info", ofType: "plist") {
    if let contents = FileManager.default.contents(atPath: path) {
      information = try? PropertyListDecoder().decode(Application.Information.self, from: contents)
    }
  }
```

At that point, I don't think that this is sufficiently simple to just inline into the single call site.

2021-02-20 17:13 UTC, compnerd commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +  if let application = application != nil ? application : information?.principalClass {
The `nil`-cascading operation is clearer:

```swift
let application: String = application ?? (information?.principalClass ?? NSStringFromClass(Application.self))
guard let instance = NSClassFromString(application) else {
  log.error("unable to find application class \(application)")
  exit(EXIT_FAILURE)
}
Application.shared = (instance as! Application.Type).init()
Application.shared.information = information
```

2021-02-20 18:58 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +    log.warning("Failed to load contents of info.plist")
Indded I agree

2021-02-20 19:02 UTC, yostane commented on Sources/SwiftWin32/Application/ApplicationMain.swift
> +func getApplicationClassName(userPassedApp: String?, appInformation: Application.Information?) -> String?{
Nice ! I'll take a look

2021-02-20 19:11 UTC, yostane commented on Examples/CMakeLists.txt
> -
Ideed XD

2021-02-21 18:34 UTC, compnerd approved these changes
Unfortunate that it took so many rounds to convey the simplicity of the change, but thank you for the perseverance and the change :)

2021-02-21 18:38 UTC, merged

2021-02-21 22:42 UTC, yostane commented
You're welcome. It's ok for me to take the necessary time, it's not like there are project deadlines to meet XD.

Thanks for the kind and interesting reviews.