Added PrincipalClass documentation
compnerd/swift-win32 pull request #393
Opened 2021-02-25 20:30 UTC by yostane

2021-02-27 00:51 UTC, compnerd requested changes

2021-02-27 00:51 UTC, compnerd commented on Documentation/PrincipalClass.md
> +```
I think that this belongs in a separate section if you want to cover how to use this with CMake.

2021-02-27 00:51 UTC, compnerd commented on Documentation/PrincipalClass.md
> +- In `Info.plist`, define a `PrincipalClass` entry with a String value of `{AppName}.{CustomClassName}`. For example, if the application is named `CustomPrincipalClass`, then we can register `MyAppli
I don't think that `{AppName}.{ClassName}` is the right pattern.  It is supposed to be `{Module}.{Class}` I believe.  There is no guarantee that the application and module name are the same.

2021-02-27 00:51 UTC, compnerd commented on Documentation/PrincipalClass.md
> +- You can reference your custom application subclass anywhere in you app by casting `Application.shared` to your custom application class. For example, here is how to print the `message` property of
This is documenting `Application` rather than the `PrincipalClass`.  I think that should be separate.

2021-03-02 20:38 UTC, yostane commented on Documentation/PrincipalClass.md
> +- You can reference your custom application subclass anywhere in you app by casting `Application.shared` to your custom application class. For example, here is how to print the `message` property of
Maybe something like this shows how to get a reference to the PrincipalClass without documenting Application   ?

`The application now uses the class defined in PrincipalClass instread of the default one. For example, here is how to print the `message` property of the `MyApplication` subclass defined above:`

2021-03-02 20:39 UTC, yostane commented on Documentation/PrincipalClass.md
> +- In `Info.plist`, define a `PrincipalClass` entry with a String value of `{AppName}.{CustomClassName}`. For example, if the application is named `CustomPrincipalClass`, then we can register `MyAppli
Yes I agree :)

2021-03-04 18:58 UTC, compnerd commented on Documentation/PrincipalClass.md
> +- You can reference your custom application subclass anywhere in you app by casting `Application.shared` to your custom application class. For example, here is how to print the `message` property of
I think that it would be more useful to document why/when it is useful to actually provide a custom principal class.  This would allow you to focus on the details of the principal class rather than how to get the instance.

2021-03-20 08:54 UTC, yostane commented on Documentation/PrincipalClass.md
> +- You can reference your custom application subclass anywhere in you app by casting `Application.shared` to your custom application class. For example, here is how to print the `message` property of
From my research, I found that PrincipalClass is mostly used in plugin scenarios for macOS / Cocoa's loadable bundles or in extensions. The princial class allows to get the entry point of the plugin.
Is it possible to create a plugin or extension on SwiftWin 32 ?

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingCode/Tasks/CreatingBundles.html

2021-03-20 16:55 UTC, compnerd commented
Thanks!  This looks great.  I think that a good follow up here would be to actually describe what the principal class is, but this looks good to merge as is, we can enhance the documentation further in subsequent changes.

2021-03-20 16:55 UTC, compnerd approved these changes

2021-03-20 16:56 UTC, merged

2021-03-20 16:56 UTC, compnerd commented
Oh, another item that could be useful to add is how to control this via the API rather than `Info.plist` (although, for most cases, the plist approach is better).