WIP: First lines of views and controls documentation
compnerd/swift-win32 pull request #422
Opened 2021-03-20 18:30 UTC by yostane

Hello  @compnerd ,

Can you check if this kind of doc is ok for views and controls. I explained that the API is similar to UIKit and that the implementation id provided by win32. If it's alright, I will fill the table with remaining views and controls.

Thanks :),

2021-03-20 20:25 UTC, compnerd commented
I think that documenting the various views and controls is a good idea.  I think that I might try to figure out how to create a kanban board (project) to track all the items for documentation.  I think that the details of the implementation are more developer oriented than user oriented.  Currently, the documentation is largely user facing, so we should cover the details of what the interfaces are and how they should be and can be used.  I don't have a problem with more developer oriented documentation, but perhaps that should be a separate set of documentation.

2021-04-14 13:51 UTC, yostane commented
Hi @compnerd. Can you review 😃 ?

2021-04-15 21:20 UTC, compnerd requested changes

2021-04-15 21:20 UTC, compnerd commented on Documentation/ViewAndControls.md
> +The visual component library API is inspired by [UIKit](https://developer.apple.com/documentation/uikit/views_and_controls) but their actual implementation is provided by [win32 windows controls](htt
I believe that the `Windows Common Controls` is the proper name for this subsystem.  I don't think that `win32` is a good idea to use - it can be confusing - do you mean the win32 subsystem?  Do you mean the win32 apis?  Or do you mean 32-bit windows?  The term is somewhat context sensitive, and it might be better to be more precise in general.

2021-04-22 08:02 UTC, yostane commented on Documentation/ViewAndControls.md
> +The visual component library API is inspired by [UIKit](https://developer.apple.com/documentation/uikit/views_and_controls) but their actual implementation is provided by [win32 windows controls](htt
Thanks for the feedback. I updated the text accordingly.

2021-04-24 02:53 UTC, compnerd requested changes

2021-04-24 02:53 UTC, compnerd commented on Documentation/ViewAndControls.md
> +For example: the `Label` has a similar API than UIKit's `UILabel` and is drawn using the `WC_STATIC` Windows control.
This is not grammatically correct.  The `WC_STATIC` is not a Windows control per se.  It is the name of a window class.

```suggestion
For example: the `Label` has an API similar to UIKit's `UILabel` and is drawn using the `WC_STATIC` Windows window class.
```

2021-04-24 02:53 UTC, compnerd commented on Documentation/ViewAndControls.md
> +| Swicth       | WC_BUTTON          | A control that offers two choices                        |
One thing which is still unclear is who this documentation is useful for.  This doesn't seem material to users of Swift/Win32, so perhaps we should have a separate documentation group for Swift/Win32 developers?

2021-04-24 04:58 UTC, compnerd commented
BTW, I am experimenting with getting something better for documentation.  http://swift-win32.compnerd.org/ is something as a temporary thing, but its auto-generated, and I do expect that we can get auto-generated and updated per-commit.  It is generated directly from the sources.  Given your previous interest in the documentation, I think your thoughts on this could be valuable.

2021-04-24 10:56 UTC, yostane commented
Hi. Thanks for the share :). What a coincidence, I was also just going to suggest adding an auto-generated documentation in addition to the manual one. I think that both will complement each other.

I was also going to suggest to publish the documentation on a website. In my opinion, the website should have the following structure:

- Home page with a link to a getting started page, a guide and a documentation
- A getting started page shows how to setup the prerequisites and how to create a hello world project
- The guides act a a series of tutorials. For example: How create a new project, how to perform typical use cases
- The documentation is the auto-generated doc

What do you think ?

2021-04-24 17:01 UTC, compnerd commented
My current thoughts are to use swift-doc to (auto-)generate the documentation, which doesn't give as much control over the structure.  However, my knowledge of swift-doc is also pretty limited (I've only recently started getting that to work on Windows).  I think that the pre-requisites should really be covered in the README.  Detailed documentation on usage I think does also belong in-line with the source code.  The homepage idea is great, unfortunately, I do not have the necessary skills to do that job well and I think is something beyond the scope of the project itself, but related work.  I think that using GH Pages to create a static site as a "homepage" is a great idea though.  That largely covers bullets 1 and 4, and partially bullet 2.

Thinking a bit longer term, I think that I would like to _remove_ the HelloWorld example and convert that into a template instead.  I would like to convert that into a project template for VSCode.  Having additional documentation in the template for getting the user setup and productive would be a good idea.

For the guides, I think that if we have the static pages, we should be able to add them there and incorporate them into the site.  I think that we should have two modules that have documentation:
1. SwiftWin32: the core "raw" API surface
2. SwiftWin32UI: the SwiftUI wrapper layer
This also would require additional guides and work to have two different documentation trees.

This requires some adjustment over what I have currently, but if we have the static pages to home the documentation, I think that this could work very well and solves the problem really well, and was something that I hadn't considered.

2021-04-26 21:49 UTC, yostane commented
Great, I was also thinking about creating the homepage on gh-pages. I have some experience on that subject with the help of [vuepres](https://vuepress.vuejs.org/). Here is an example of a project I worked on with a friend https://github.com/sylvainpolletvillard/pwa-workshop. I also found some makrdown-based tools that should help us do the job: 

- https://github.com/mkdocs/mkdocs
- https://bumped.github.io/
- https://docsify.js.org/#/quickstart

I can try to do a simple PR to see what it looks like. If you have a preference for a particular tools, I can try that one :).

About having a HelloWorld template project, I also agree that would be cool.

2021-04-26 23:58 UTC, compnerd commented
What do you think of using jekyll for this?  That would allow us to use the general infrastructure from GitHub to support this.

My current thought is to have a 3 branch structure:
- main (sources)
- website (sources for the website)
- gh-pages (current release)

The idea is that a change to main would trigger a job which would clone the current state of the website branch, generate new documentation, (force) push to the gh-pages.  It would then allow compnerd.github.io/swift-win32 to point to the gh-pages branch.

2021-04-27 09:06 UTC, yostane commented
Ok for using jekyll. I'll try to push a website branch. If my understanding is correct, the website branch contains only documentation code and files.

I will follow this tutorial unless you have a more suitable guide :) https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll

2021-04-27 10:51 UTC, yostane commented on Documentation/ViewAndControls.md
> +| Swicth       | WC_BUTTON          | A control that offers two choices                        |
In my mind, I was targeting users of swift/win32. I agree that the second column in not necessary because I already mentioned that the Windows common controls are used and that's enough to know as a user of the library.

2021-04-27 21:07 UTC, compnerd commented
> If my understanding is correct, the website branch contains only documentation code and files.

The website branch should only have the website markdown files (from an empty history).  The documentation would be something we would autogenerate and merge and push to gh-pages.

2021-05-09 18:55 UTC, yostane commented
Hi. I have initiated a jekyll project on my [fork](https://github.com/yostane/swift-win32) and manually published it [here](https://yostane.github.io/swift-win32/). Can you take a look please and provide any feedback :) ?

About automating the deployment of the website, should it be configured in *azure-pipelines.yml* ?

2021-05-09 23:55 UTC, compnerd commented
Nice!  I think I generally like the idea overall.  I think I would like to get the screenshot on the default view (under the description of the project).

I think that the deployment would be best done as a github action.  I think that should be a push action.  I think that the actual GHA setup should be pretty easy, just need to figure out what the action should do in terms of "building" (basically what commands if any need to be run to pre-process any data.  I should be able to setup the job to run the command(s) on push to the website branch.

Do you think that Chirpy would be compatible?  http://jekyllthemes.org/themes/jekyll-theme-chirpy/

I assume that changing the theme should be relatively easy further down the line anyways right?

2021-05-10 20:13 UTC, yostane commented
Thanks for the feedback, I'll try to integrate the image as suggested.

> I think that the deployment would be best done as a github action
ok :). I'll also try to play with GHA when possible, I've never used it before.

>Do you think that Chirpy would be compatible? http://jekyllthemes.org/themes/jekyll-theme-chirpy/
From what I've seen in the demo, this theme is more oriented towards blogging. For example, pages are likely to be sorted by creation date while 'just-the-docs' allows the user the set the order of the pages. So, with respect to pure documentation, I don't think that this plugin is a good fit in my opinion. 

>I assume that changing the theme should be relatively easy further down the line anyways right?
The transition should be easy, but some theme features may require some additional work to be fully . For example

2021-05-11 15:37 UTC, compnerd commented
Okay, I consider https://compnerd.github.io/swift-win32/SwiftWin32 live now.  It is auto-generated on any merge to main.  We should be able to do something to merge in content from a website branch when generating the project.  You should be able to tweak the github action for documentation on your fork to play around with this.

2021-05-12 16:59 UTC, compnerd commented
@yostane Id like to populate part of the website branch earlier rather than later.  In particular, I would like to get the `_config.yml` file checked in.  The motivation for that is that it currently prevents certain pages for the documentation from being rendered.  Do you have any thoughts on what would be the best thing to do here so that it doesn't conflict with the work that you are doing?

2021-05-12 17:30 UTC, yostane commented
@compnerd if my understating is correct, you are willing to create a documentation branch on the main repo.  In that case, you can populate the website branch as you see fit. Once the branch documentation has been pushed, I can fork it and continue my work :). Otherwise, you can populate the branch as you see fit and I will try to adapt consequently.

2021-05-12 17:30 UTC, yostane commented
@compnerd if my understating is correct, you are willing to create a documentation branch on the main repo.  In that case, you can populate the website branch as you see fit. Once the branch documentation has been pushed, I can fork it and continue my work :). Otherwise, you can populate the branch as you see fit and I will try to adapt consequently.

2021-05-12 17:41 UTC, yostane commented
> In particular, I wanted the ability to toggle light/dark variants and syntax highlighting.

just-the-doc provides a dark mode through a setting https://pmarsceill.github.io/just-the-docs/docs/configuration/. It also has nice code display features https://pmarsceill.github.io/just-the-docs/docs/ui-components/code/

2021-05-12 17:42 UTC, compnerd commented
Well, a website branch for the static content that is not entirely documentation.  Id like to have the API documentation be auto-generated, higher level documentation be static documentation (unless there is a way to integrate that into the API documentation).  The idea is that the content of gh-pages would be the combination of the static content of the website branch and the auto-generated content from the sources.

2021-05-12 18:10 UTC, yostane commented
> (unless there is a way to integrate that into the API documentation)

I have these suggestions: 
1. It looks like a tool called [jazzy](https://github.com/realm/jazzy) allows to have autogenerated docs + user created docs. Here is an example: https://jessesquires.github.io/JSQCoreDataKit/index.html (there is even a [guide](https://www.jessesquires.com/blog/2016/05/20/swift-documentation/))
1. I have noted that swift-doc can generate markdown. We could do try to do something like this but I don't know if it will work:
  - Generate markdown swift-doc
  - Add it to the jekyll documentation (we will need to add content to each file such a header)
  - Let jekyll build the manual + automatic markdown
1. Same as earlier but we try with the html auto-generated doc

If we can't find a way to integrate the two docs, the only remaining possibility is to provide a link to the autogenerated docs from the high level (manual) docs.

2021-05-12 18:26 UTC, compnerd commented
I think that trying to get jazzy to work on Windows is not worth the effort.  I have swift-doc already working on Windows.  Additionally, the ruby dependency in jazzy makes it harder for me to test locally.

Currently, I am generating the HTML docs.  I don't have a problem with generating the markdown docs instead.  It should be a pretty straightforward thing to change.

2021-05-12 19:19 UTC, yostane commented
ok we can try that 👍

2021-05-13 16:09 UTC, compnerd commented
I seem to be unable to figure out what is needed to get the theming to apply to the GitHub pages :-(.  Could you please take a look @yostane?  The content is on the website branch.

2021-05-15 15:29 UTC, yostane commented
Maybe the problem comes from the include option which makes the build fail. Do you have an error message when you go to "settings" -> "pages" ?

Here is an example of using wildcards in the config file: https://github.com/jekyll/jekyll/issues/948#issuecomment-16269424

2021-05-15 16:03 UTC, compnerd commented
Well, that was embarrassing.  Thank you, that was in fact the problem, the missing quotes.  It is slightly better now in that it renders the theme, but it still didn't fix what I was hoping it would.  There are pages which are getting excluded because the path includes `_` prefixed directories (e.g. https://compnerd.github.io/swift-win32/SwiftWin32/_TriviallyConstructible).  Thoughts on how to fix that would be appreciated.  But this definitely needs a lot more work work to get into a good state.  Perhaps the ideas that you have for converting to markdown instead of html generation will help address this.

2021-05-17 00:19 UTC, compnerd commented
Okay, the change to the common mark emission is easy enough, the problem is that the structure is completely lost as a result.  I think that we need to do some amount of post-processing to make it fit within the structure (namely we need the front matter for the children to get the categorization correct).

2021-05-18 05:10 UTC, compnerd commented
I wonder if we can generate the images using swift-doc and integrate them somehow to get an overview of the type hierarchy for the interfaces.  It might make it easier/nicer to navigate.

BTW, I'm working somewhat to extract a template project for getting started.

2021-05-18 12:50 UTC, yostane commented
It seems that we can achieve that with swift-doc + graphviz. 

> BTW, I'm working somewhat to extract a template project for getting started.

Great news, I'll be glad to try it out when its ready.

2021-05-18 13:17 UTC, yostane commented
Here is the image that I get when I run:

```sh
swift-doc diagram .\Sources\SwiftWin32\ > swiftwin32.gv
dot -T svg .\swiftwin32.gv > .\swiftwin32.svg
```

![swiftwin32](https://user-images.githubusercontent.com/1958676/118657720-017bfd80-b7ec-11eb-8887-4207eec4ddde.png)

I find it a bit weird, maybe we can improve it by setting different arguments to the dot command ?

2021-05-18 13:48 UTC, yostane commented
You can visualize [here](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0D%0A%20%20subgraph%20cluster_View%20%7B%0D%0A%20%20%20%20%20%20TableViewHeaderFooterView%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20TableView%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20Control%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20TableViewCell%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20ImageView%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20TextView%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20TableViewHeaderFooterView%20-%3E%20View%0D%0A%20%20%20%20%20%20TableView%20-%3E%20View%0D%0A%20%20%20%20%20%20Control%20-%3E%20View%0D%0A%20%20%20%20%20%20TableViewCell%20-%3E%20View%0D%0A%20%20%20%20%20%20ImageView%20-%3E%20View%0D%0A%20%20%20%20%20%20TextView%20-%3E%20View%0D%0A%20%20%7D%0D%0A%20%20subgraph%20cluster_View%20%7B%0D%0A%20%20%20%20%20%20TextField%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20DatePicker%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20Stepper%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20Switch%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20Button%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20Slider%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20ProgressView%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20Label%20%5Bshape%3Dbox%5D%0D%0A%20%20%20%20%20%20TextField%20-%3E%20Control%0D%0A%20%20%20%20%20%20DatePicker%20-%3E%20Control%0D%0A%20%20%20%20%20%20Stepper%20-%3E%20Control%0D%0A%20%20%20%20%20%20Switch%20-%3E%20Control%0D%0A%20%20%20%20%20%20Button%20-%3E%20Control%0D%0A%20%20%20%20%20%20Slider%20-%3E%20Control%0D%0A%20%20%20%20%20%20ProgressView%20-%3E%20Control%0D%0A%20%20%20%20%20%20Label%20-%3E%20Control%0D%0A%20%20%7D%0D%0A%20%20%22View.ContentMode%22%20-%3E%20Int%0D%0A%20%20%22View.AutoresizingMask%22%20-%3E%20OptionSet%0D%0A%20%20%22View.AnimationCurve%22%20-%3E%20Int%0D%0A%20%20View%20-%3E%20Equatable%0D%0A%20%20View%20-%3E%20Responder%0D%0A%20%20View%20-%3E%20TraitEnvironment%0D%0A%20%20TextFieldDelegate%20-%3E%20AnyObject%0D%0A%20%20TextAlignment%20-%3E%20Int%0D%0A%20%20TextField%20-%3E%20TextInputTraits%0D%0A%20%20TableViewFocusUpdateContext%20-%3E%20FocusUpdateContext%0D%0A%20%20TableViewDelegate%20-%3E%20AnyObject%0D%0A%20%20TableViewDataSource%20-%3E%20AnyObject%0D%0A%20%20%22TableViewCell.CellStyle%22%20-%3E%20Int%0D%0A%20%20%22TableViewCell.EditingStyle%22%20-%3E%20Int%0D%0A%20%20%22TableView.Style%22%20-%3E%20Int%0D%0A%20%20%22ContextualAction.Style%22%20-%3E%20Int%0D%0A%20%20%22Switch.Style%22%20-%3E%20Int%0D%0A%20%20EdgeInsets%20-%3E%20Equatable%0D%0A%20%20DirectionalRectEdge%20-%3E%20OptionSet%0D%0A%20%20DatePickerStyle%20-%3E%20Int%0D%0A%20%20%22Control.State%22%20-%3E%20OptionSet%0D%0A%20%20%22Control.Event%22%20-%3E%20Equatable%0D%0A%20%20%22Control.Event%22%20-%3E%20Hashable%0D%0A%20%20%22Control.Event%22%20-%3E%20RawRepresentable%0D%0A%20%20Axis%20-%3E%20OptionSet%0D%0A%7D%0D%0A) the graph of /swiftwin32/views and controls :)

2021-05-18 15:12 UTC, compnerd commented
Right, I think that figuring out how to invoke swift-doc to visualize the subtree would be the thing to do here (or possibly enhance it further if it is not possible).  The HTML rendering actually provides clickable images (via SVG) that link the type hierarchy together.    But at the very least we now have the ability to start adding more documentation, and it should all get auto-regenerated.  I know that the documentation for the interfaces is pretty lacking currently, but hopefully we can get that improved.  Plus, the new linting CI jobs also should help ensure that we get doc-comments for new public interfaces.

As to the template repository: https://github.com/compnerd/swift-win32-application is the current state.  I'll likely improve it continuously, but should at least give a good starting point for an application.  I'm still struggling to figure out how to best template it so that someone can easily get started with that.

2021-05-30 18:16 UTC, compnerd commented
BTW, this is now on the wrong branch, it really should be either documentation in the source code (ideal) or should be static content in the website branch.

2021-07-23 16:51 UTC, compnerd commented
I'm going to close this branch as it is pretty stale at this point.  Please feel free to either re-open or create a new PR to continue the work on the documentation.

2021-07-23 16:51 UTC, closed without merging