Add decoder for giving name for messages sent to WindowProcs
compnerd/swift-win32 pull request #454
Opened 2021-04-08 18:25 UTC by rjpilgrim

I have added support for decoding the uMsgs into their Win32 macro names. This makes it far easier to understand the messages coming into a view at runtime.

Example usage for decoding messages:

```
private let SwiftButtonProc: SUBCLASSPROC = { (hWnd, uMsg, wParam, lParam, uIdSubclass, dwRefData) in
  let button: Button? = unsafeBitCast(dwRefData, to: AnyObject.self) as? Button
  print("Button receive message: \(getStringforMsg(uMsg))")
  ...
}
```

2021-04-08 18:35 UTC, compnerd requested changes

2021-04-08 18:35 UTC, compnerd commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> + **/
Please copy the standard header in the project, replacing the author as yourself.

2021-04-08 18:35 UTC, compnerd commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +class Win32MessageDecoder {
Why is this a `class`?  There doesn't seem to be anything that needs a reference type here.

2021-04-08 18:35 UTC, compnerd commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +	static func getStringforMsg(_ uint: UINT) -> String {
I wonder if we can create a `WindowMessage` type, and then use `CustomStringConvertible` instead?  WDYT?

2021-04-08 18:35 UTC, compnerd commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +	static let messages : [Int : String] = {
The style of the project uses 2-space indents, could you reformat the file please?  I can try to add a swift format configuration file and try to write up some style documentation later.

2021-04-08 19:00 UTC, rjpilgrim commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> + **/
This has been done.

2021-04-08 19:04 UTC, rjpilgrim commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +	static func getStringforMsg(_ uint: UINT) -> String {
I do not see much value in creating a new type here, considering that the only use of the type would be for the use of its text representation. Such a type could be useful if the callbacks themselves could be made to work with WindowMessage, but I expect you would have to make a C wrapper to handle such functionality, which may be more effort than it is worth.

2021-04-08 19:04 UTC, rjpilgrim commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +	static let messages : [Int : String] = {
I restyled the file with spaces.

2021-04-08 20:14 UTC, compnerd commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +	static func getStringforMsg(_ uint: UINT) -> String {
I just don't see a way to constrain the conformance.  Adding the conformance to `UINT` is overly broad.  I suppose we could do `WindowMessage.debugDescription(for:)` instead.

2021-04-08 20:16 UTC, compnerd commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +  static let messages : [Int : String] = {
What does this accomplish exactly?  Im not sure I understand this part still.  Can we not just use the static mapping below?

2021-04-14 21:33 UTC, rjpilgrim commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +  static let messages : [Int : String] = {
The static mapping has duplicates, I am not sure the best way to handle these. I am currently pruning the Static Mapping of _FIRST and _LAST entries, as those are especially unhelpful, but I am not sure if there is a way to resolve messages to their name considering I have only access to a number for the sake of decoding.

2021-04-14 21:38 UTC, rjpilgrim commented on Sources/SwiftWin32/Support/Win32MessageDecoder.swift
> +  static let messages : [Int : String] = {
The static mapping is transposed from the following source: https://wiki.winehq.org/List_Of_Windows_Messages

2021-04-14 21:59 UTC, rjpilgrim commented
I have went ahead and renamed the Decoder to WindowMessage, with a function debugDescription. This is the implementation I believe you were dsecribing.

Usage now becomes:

```
private let SwiftButtonProc: SUBCLASSPROC = { (hWnd, uMsg, wParam, lParam, uIdSubclass, dwRefData) in
  let button: Button? = unsafeBitCast(dwRefData, to: AnyObject.self) as? Button
  print("Button receive message: \(WindowMessage.debugDescription(for: uMsg))")
  ...
}
```

2021-04-15 21:20 UTC, compnerd commented
Thank you, that is indeed the interface that I had in mind.  Would you mind rebasing the change so that it is easier to review?

2021-04-16 14:29 UTC, rjpilgrim commented
I have rebased on top of the current main.

2021-04-16 14:35 UTC, rjpilgrim commented
I don't think that I've used the best method for resolving the file name change during the rebase. The commit history is confusing.

2021-04-16 14:45 UTC, rjpilgrim commented
I've shrunk the commits down into one.

2021-04-16 15:58 UTC, compnerd requested changes

2021-04-16 15:58 UTC, compnerd commented on Sources/SwiftWin32/Support/WindowMessage.swift
> +    return "Unknown Message"
This could be written more succinctly as:

```suggestion
    return messages[Int(uMsg)] ?? "Unknown Message"
```

2021-04-16 15:58 UTC, compnerd commented on Sources/SwiftWin32/Support/WindowMessage.swift
> +    var messages : [Int : String] = [:]
```suggestion
    var messages: [Int:String] = [:]
```

2021-04-16 15:58 UTC, compnerd commented on Sources/SwiftWin32/Support/WindowMessage.swift
> +    return messages
I'm still not convinced of the value of this.  The duplicated values end up discarded anyways, why have them listed in the first place?

2021-04-16 15:58 UTC, compnerd commented on Sources/SwiftWin32/Support/WindowMessage.swift
> +    return messages
This seems more complicated than necessary.

```suggestion
    return Dictionary<Int, String>(keyValues, uniquingKeysWith: { (first, _) in first })
```

2021-04-16 15:58 UTC, compnerd commented on Sources/SwiftWin32/Support/WindowMessage.swift
> +}
Missing newline.

```suggestion
}
```

2021-04-16 15:58 UTC, compnerd commented on Sources/SwiftWin32/Support/WindowMessage.swift
> +  static func debugDescription(for uint: UINT) -> String {
```suggestion
  static func debugDescription(for uMsg: UINT) -> String {
```

2021-04-16 18:04 UTC, rjpilgrim commented
I am currently working to remove all duplicates from Dictionary literal, allowing it to be used to instantiate messages. Duplicated messages will show up as follows: "MSG_FTS_JUMP_QWORD || RB_SHOWBAND || TB_GETTOOLTIPS" for instance for 1059.

2021-04-16 18:53 UTC, rjpilgrim commented
Reworked the approach to duplicate messages. Some of the resulting strings are a bit long, but I think it is important to preserve the information.

2021-04-17 04:30 UTC, compnerd approved these changes
Sure, this works for now.  We can always clean it up subsequently.  I think that there might actually be some use in explicitly building up some infrastructure for decoding messages.

2021-04-17 04:30 UTC, compnerd commented
/azp run VS2019

2021-04-17 04:37 UTC, merged